service: webrivage-foosball-api

plugins:
  - serverless-plugin-typescript
  - serverless-mocha-plugin

provider:
  name: aws
  runtime: nodejs6.10

  region: eu-west-1

  stage: ${opt:stage, 'dev'}

  memorySize: 128

functions:

  www:
    handler: src/API/handler.index
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
